CREATE TABLE `TB_SPREAD_REQUEST_BAS` (
  `Token` varchar(3) NOT NULL,
  `ROOM` varchar(10) NOT NULL,
  `RG_REQUEST_DATE` datetime NOT NULL,
  `USER` int NOT NULL,
  `RG_TOTAL_MONEY` int NOT NULL,
  `RG_USER_COUNT` int NOT NULL,
  PRIMARY KEY (`Token`,`ROOM`,`RG_REQUEST_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci